# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/erikp/Desktop/Egyetem/3_Felev/Ujrakonfiguralhato Aramkorok/Projektek/VGA_BOUNCE/VGA_BOUNCE.srcs/sources_1/ip/loons240x160/loons240x160.xci
# IP: The module: 'loons240x160' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/erikp/Desktop/Egyetem/3_Felev/Ujrakonfiguralhato Aramkorok/Projektek/VGA_BOUNCE/VGA_BOUNCE.srcs/sources_1/ip/loons240x160/loons240x160_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'loons240x160'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/erikp/Desktop/Egyetem/3_Felev/Ujrakonfiguralhato Aramkorok/Projektek/VGA_BOUNCE/VGA_BOUNCE.srcs/sources_1/ip/loons240x160/loons240x160.xci
# IP: The module: 'loons240x160' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/erikp/Desktop/Egyetem/3_Felev/Ujrakonfiguralhato Aramkorok/Projektek/VGA_BOUNCE/VGA_BOUNCE.srcs/sources_1/ip/loons240x160/loons240x160_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'loons240x160'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
